### ISSUE TITLE
Port forwarding with firewalld is not persistent

### ISSUE THREAD

**Issue by p3lim** [containers/netavark#723]
Steps to reproduce:

Run a container that publishes a port, e.g. nginx:

```
podman run --rm -p 8000:80 docker.io/nginx:latest
```

This yield's the following firewalld policy:

```
netavark_portfwd (active)
  priority: -1
  target: CONTINUE
  ingress-zones: ANY
  egress-zones: ANY
  services:
  ports:
  protocols:
  masquerade: no
  forward-ports:
        port=8000:proto=tcp:toport=80:toaddr=10.88.0.8
  source-ports:
  icmp-blocks:
  rich rules:
```

If I now run `firewall-cmd --reload`/`systemctl reload firewalld` because I did some other firewall changes (not necessarily related to this container), the port forwarding is now gone:

```
netavark_portfwd (active)
  priority: -1
  target: CONTINUE
  ingress-zones: ANY
  egress-zones: ANY
  services:
  ports:
  protocols:
  masquerade: no
  forward-ports:
  source-ports:
  icmp-blocks:
  rich rules:
```

I can remedy this myself by running `podman network reload --all`, but this should be handled by netavark/podman itself.

Tested with:
- firewalld 1.1.1 (from Ubuntu 22.04 repos)
- podman 4.5.1 (from kubic)
- netavark 1.3.0 (from kubic)

Let me know if this should be raised in the podman repo instead.
