### ISSUE TITLE
RFC: consider read only sysctl errors as non fatal

### ISSUE THREAD

**Issue by Luap99** [containers/netavark#825]
When running inside of unprivileged containers /proc is normally mounted read only.
Now if a users tries to run netavark it will fail hard if we cannot set all the sysctl's. Most of them are needed for routing or to disable some ipv6 options but general communication may still be possible.

We should consider not treating read only errors as fatal and just log them as warning. The biggest problem is likely the ip_forward sysctl, without it no external communication would be possible. However this could already be set by the outer container manager in which case I would expect it to mostly work fine. 

see https://github.com/containers/podman/issues/19991

**Comment by dnewhook** [comment]
Did this PR try to fix this issue?  https://github.com/containers/netavark/issues/825

**Comment by Luap99** [comment]
What PR? You link to this issue.

**Comment by dnewhook** [comment]
Thanks for the info.  The right sysctls being mentioned in the following issue right?  https://github.com/containers/netavark/issues/362
```
--kubelet-extra-args '--allowed-unsafe-sysctls="net.ipv4.conf.default.route_localnet"'
```

**Comment by Omar007** [comment]
I ran into this today setting up a rootless and unprivileged podman deployment inside of a k8s cluster. Here is the PodSpec for reference:

```yaml
containers:
  - image: quay.io/podman/stable:v4.9.0
    name: podman
    command:
      - podman
      - system
      - service
      - --log-level
      - debug
      - --transient-store
      - --time
      - "0"
      - $(DOCKER_HOST)
    env:
      - name: DOCKER_HOST
        value: tcp://localhost:2375
    ports:
      - name: podman
        containerPort: 2375
        protocol: TCP
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
    resources:
      limits:
        squat.ai/fuse: 1
        squat.ai/tun: 1
```

I would've expected it to only set hard-required sysctls and ignore/not write any that already have the correct value or are optional but it seems it just tries to set them unconditionally causing problems for this setup.  

I had tried to set the following sysctls using the PodSpec's `securityContext.sysctls` field as needed (from what I can tell) to no avail. I also attempted a run with IPv6 disabled (`network_cmd_options=["enable_ipv6=false"]`) which took care of some of the sysctl writes (maybe from slirp4netns though, not netavark).  

| sysctl | value | note |
| ---- | ---- | ----- |
| net.ipv4.ip_forward | 1 | |
| net.ipv4.conf.default.arp_notify | 1 | |
| net.ipv6.conf.[default\|eth0].autoconf | 0 | |
| net.ipv6.conf.[default\|eth0].accept_dad | 0 | Only when enable_ipv6=true? |
| net.ipv6.conf.[default\|eth0].accept_ra | 0 | Only when enable_ipv6=true? |


Checking from within the running pods, the sysctls have the values as set on the PodSpec and match the value netavark would write (which it still did even though it's already correct).  
Logs show, for instance, `[DEBUG netavark::network::core_utils] Setting sysctl value for net.ipv4.ip_forward to 1` (it already is) and then it fails with `time="2024-02-14T17:10:53Z" level=info msg="Request Failed(Internal Server Error): netavark (exit code 1): Sysctl error: IO Error: Read-only file system (os error 30)"`
